apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-storage-claim
  # namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs
  resources:
    requests:
      storage: 2Gi
